# Auto-increment version and generate VersionInfo.cs
param(
    [string]$Config = "Release",
    [switch]$SkipIncrement
)

$versionFile = "version.txt"
$versionCs = "Source\VersionInfo.cs"

function Resolve-BuildNamespace {
    $projectDir = ".vscode"
    $candidates = Get-ChildItem -Path $projectDir -Filter "*.csproj" -File -ErrorAction SilentlyContinue
    if (-not $candidates -or $candidates.Count -eq 0) {
        return "Template"
    }

    try {
        [xml]$proj = Get-Content -Path $candidates[0].FullName -Raw
        $rootNsNode = $proj.SelectSingleNode('/Project/PropertyGroup/RootNamespace')
        if ($rootNsNode -and -not [string]::IsNullOrWhiteSpace($rootNsNode.InnerText)) {
            return $rootNsNode.InnerText.Trim()
        }
    }
    catch {
        # Fall through to default namespace if project parsing fails.
    }

    return "Template"
}

# Read current version
$ver = [decimal](Get-Content $versionFile -Raw).Trim()

# Increment version unless skip flag is set
if (-not $SkipIncrement) {
    $ver += 0.001
    $ver = [Math]::Round($ver, 3)
    # Write back to file
    Set-Content $versionFile $ver.ToString('0.000')
}

# Determine build type
$buildType = if ($Config -eq 'Debug') {'D'} else {'R'}
$versionString = "$ver($buildType)"
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$buildNamespace = Resolve-BuildNamespace

# Generate VersionInfo.cs
$cs = @"
// Auto-generated by update-version.ps1 - DO NOT EDIT MANUALLY
// Build timestamp: $timestamp
// Build configuration: $Config

namespace $buildNamespace
{
    public static class BuildVersion
    {
        public const string Version = "$versionString";
        public const string VersionNumber = "$ver";
        public const string BuildType = "$buildType";
        public const string BuildConfig = "$Config";
        public const string BuildTimestamp = "$timestamp";
    }
}
"@

Set-Content $versionCs $cs

Write-Host "Version updated to: $versionString"
