// Auto-generated by update-version.ps1 - DO NOT EDIT MANUALLY
// Build timestamp: 2026-04-29 09:13:48
// Build configuration: Release

namespace ProperShotguns
{
    public static class BuildVersion
    {
        public const string Version = "0.001(R)";
        public const string VersionNumber = "0.001";
        public const string BuildType = "R";
        public const string BuildConfig = "Release";
        public const string BuildTimestamp = "2026-04-29 09:13:48";
    }
}
